version: "3"
services:
  hub:
    build:
      context: .
    container_name: hub
    restart: unless-stopped
    volumes:
      - ./server:/server
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
