version: "3"
services:
  hub:
    build:
      context: .
    container_name: hub
    restart: unless-stopped
    volumes:
      - ./server:/server
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
        mode: host
